### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Krystal-crypto** [PluginBugs/Issues-RPGMoney#2]
Server version Yatopia 1.16.4 latest build
Client version 1.16.4
Plugin RpgMoney 1.1.24
![image](https://user-images.githubusercontent.com/77343023/104338768-25a29780-54f7-11eb-8256-228c9a49b016.png)
![image](https://user-images.githubusercontent.com/77343023/104338790-2cc9a580-54f7-11eb-991d-ea7f07af32e9.png)
![image](https://user-images.githubusercontent.com/77343023/104338811-3226f000-54f7-11eb-8221-3cc94eb61555.png)

mobs.yml:
https://pastebin.com/xuQcG0J5

fishes.yml:
https://pastebin.com/sZVPnesh

**Comment by LoneDev6** [comment]
Did you change anything in the config? Seems there is a problem with a mob in mobs.yml file, about the nerf options

**Comment by LoneDev6** [comment]
> 
> 
> Server version Yatopia 1.16.4 latest build
> Client version 1.16.4
> Plugin RpgMoney 1.1.24
> ![image](https://user-images.githubusercontent.com/77343023/104338768-25a29780-54f7-11eb-8256-228c9a49b016.png)
> ![image](https://user-images.githubusercontent.com/77343023/104338790-2cc9a580-54f7-11eb-991d-ea7f07af32e9.png)
> ![image](https://user-images.githubusercontent.com/77343023/104338811-3226f000-54f7-11eb-8221-3cc94eb61555.png)
> 
> mobs.yml:
> https://pastebin.com/xuQcG0J5
> 
> fishes.yml:
> https://pastebin.com/sZVPnesh

this is wrong: 4.0-4.0
you just have to set: 4.0

```yml
FISH:
  enabled: true
  money: 5.0
  numberOfMoneyDrops: 1-2
  chance: 100
  ```

instead of 

```yml
FISH:
  enabled: true
  money: 5.0-5.0
  numberOfMoneyDrops: 1-2
  chance: 100
  ```
