### ISSUE TITLE
[BUG] Player money drop

### ISSUE THREAD

**Issue by yorik100** [PluginBugs/Issues-RPGMoney#36]
**Describe the bug**
Player drops money from fall damage even if "onlyByPlayer" is set to true

**To Reproduce**
1. Fall from death
2. Drop money despite "onlyByPlayer" being disabled

**Expected behavior**
No money getting dropped

**Info (please complete the following information):**
 - Server version: Spigot 1.19.4
 - Client version: Fabric 1.19.4
 - Plugin version: 1.1.32-r2

**Comment by yorik100** [comment]
Was due to
natural_death:
  enable_drop: true

Not clear enough, I supposed it was natural deaths from mobs (like sheep dying from fire)

**Comment by LoneDev6** [comment]
I'll make this more clear in the wiki in the next days

**Comment by LoneDev6** [comment]
Natural death settings are now moved to the loot file itself, not global.
```yml
player:
  enabled: true
  entities:
    - PLAYER
  money: 5%
  chance: 100
  only_if_killer_is_a_player: true
  natural_death:
    enable: true
    percentage_of_money: 35
  worlds:
    - world
```

`only_if_killer_is_a_player` allows you to decide if loots will be dropped only if the killer is a player (and not a natural cause)
`natural_death.enabled` allows you to decide if you want natural death to drop any money, if yes how much percentage of it will be dropped can be specified using `percentage_of_money`.
