### ISSUE TITLE
[Suggestion] add custom sounds pickup money with ItemsAdder

### ISSUE THREAD

**Issue by MrJorman** [PluginBugs/Issues-RPGMoney#8]
soundOnMoneyPickup:
  enabled: true
  type: ENTITY_EXPERIENCE_ORB_PICKUP
  volumn: 2.0
  pitch: 1.0
  
  type: pls custom sounds in my ItemsAdder

**Comment by LoneDev6** [comment]
Thanks, this will be added in the next update.
Example:
```yml
soundOnMoneyPickup:
  enabled: true
  type: itemsadder:ambient.angelic
  volumn: 2.0
  pitch: 6.0
```
